config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :sports do
    resources :numbers
    resources :trainings
    resources :players do
      resources :numbers
    end
  end

  resources :sports, only: [:destroy]
  resources :numbers
  resources :players, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/number.rb
class Number < ApplicationRecord
  belongs_to :player
  belongs_to :sport
  belongs_to :user
  has_many :trainings
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  belongs_to :sport, foreign_key: "sport_id"
  has_many :numbers
end

app/models/sport.rb
class Sport < ApplicationRecord
  belongs_to :user
  has_many :numbers
  has_many :players, dependent: :destroy
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :number
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sports
  has_many :players
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  def index
    @sport = Sport.find(params[:sport_id])
    @player = @sport.players.find(params[:player_id])
    @numbers = @player.numbers
  end

  def new
    @sport = Sport.find(params[:sport_id])
    @player = Player.find(params[:player_id])
    @number = Number.new
  end

  def create
    @sport = Sport.find(params[:sport_id])
    @player = Player.find(params[:player_id])
    @number = @player.numbers.build(number_params)
    @number.player_id = current_user.id
    @number.user_id = @player.user_id
    @number.sport_id = @sport.id

    if @number.save
      redirect_to sport_player_numbers_path(@sport, @player), flash: { success: "Les stats ont été ajoutées avec succès" }
    else
      puts @number.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  private

  def number_params
    params.require(:number).permit(:duration, :score, :sport_id)
  end
end


# <%= link_to "Voir les statistiques", url_for([@sport, @player, :numbers])

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def show
    @sport = Sport.find(params[:sport_id])
    @player = Player.find(params[:id])
  end

  def edit
    @sport = Sport.find(params[:sport_id])
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to sport_player_path(@player.sport, @player)
    else
      render :edit
    end
  end

  def new
    @sport = Sport.find(params[:sport_id])
    @player = Player.new
  end

  def create
    @sport = Sport.find(params[:sport_id])
    @player = @sport.players.build(player_params)
    @player.user = current_user

    if @player.save
      redirect_to sport_path(@sport), flash: { success: "Le joueur a été créé avec succès" }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @sport = @player.sport

    if current_user == @sport.user
      @player.destroy
      redirect_to sport_path(@sport), status: :see_other, flash: { alert: "Le joueur a été supprimé avec succès." }
    else
      render plain: "Vous n'êtes pas autorisé à supprimer ce joueur.", status: :forbidden
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :size, :height, :position)
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  def index
    @sports = current_user.sports
  end

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)
    @sport.user = current_user
    if @sport.save
      redirect_to sports_path, flash: { success: "Le sport a été créé avec succès" }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @sport = Sport.find(params[:id])
  end

  def destroy
    @sport = Sport.find(params[:id])
    if current_user == @sport.user
      @sport.destroy
      redirect_to sports_path, status: :see_other, flash: { alert: "Le dossier a été supprimé avec succès." }
    else
      render "Vous n'êtes pas autorisé à supprimer ce dossier.", status: :forbidden
    end
  end

  private

  def sport_params
    params.require(:sport).permit(:name, :teams, :sports)
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Performs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/numbers/index.html.erb
<h1>Stats du joueur <%= @player.name %></h1>
<div class="container_index-number">
  <ul>
    <% if @player.numbers.any? %>
      <% @player.numbers.each do |number| %>
        <li><%= number.score %></li>
        <li><%= number.duration %></li>
      <% end %>
    <% else %>
      <li>Aucune statistique disponible</li>
    <% end %>
  </ul>
</div>

<%= link_to "Ajouter des stats", new_sport_player_number_path(@sport, @player) %>

app/views/numbers/new.html.erb
<h1>Ajouter les stats du joueur</h1>
<%= simple_form_for [@sport, @player, @number], url: sport_player_numbers_path(@sport, @player) do |form| %>
  <%= form.input :duration %>
  <%= form.input :score %>
  <%= form.association :sport, collection: Sport.all, label_method: :name, value_method: :id, include_blank: true %>
  <%= hidden_field_tag :player_id, @player.id %>
  <%= form.button :submit, "Ajouter les stats" %>
<% end %>

app/views/pages/home.html.erb
<div class="titre_page">
  <h1>Bienvenue sur <br> PerformsSports</h1>
  <%= link_to "Vos équipe", sports_path, class: "btn btn-primary" %>
</div>

app/views/players/edit.html.erb
<h1>Mettre à jour le Joueur</h1>
<%= simple_form_for [@sport, @player], url: sport_player_path(@sport, @player) do |form| %>
  <%= form.input :name %>
  <%= form.input :size %>
  <%= form.input :height %>
  <%= form.input :position %>
  <%= form.button :submit, "Mettre à jour" %>
<% end %>

app/views/players/new.html.erb
<h1>Ajouter un nouveau Joueur</h1>
<%= simple_form_for [@sport, @player], url: sport_players_path(@sport) do |form| %>
  <%= form.input :name %>
  <%= form.input :size %>
  <%= form.input :height %>
  <%= form.input :position %>
  <%= form.button :submit, "Ajouter un nouveau joueur" %>
<% end %>

app/views/players/show.html.erb
<h1>Details joueurs</h1>
  <p>Nom: <%= @player.name %></p>
  <p>Taille : <%= @player.size %></p>
  <p>Poids : <%= @player.height %></p>
  <p>Position : <%= @player.position %></p>
  <%= link_to "Voir les statistiques", url_for([@sport, @player, :numbers]) %>
  <br>
  <%= link_to "Mettre à jour le joueur", edit_sport_player_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/sports/index.html.erb
<div class="m-3">
  <div class="titre-index-realties my-3">
    <h2>Bienvenue, <%= current_user.email %></h2>
  </div>
  <div class="container_indexsports">
    <ul>
      <% @sports.each do |sport| %>
        <p><%= sport.name %></p>
        <p><%= sport.teams %></p>
        <%= link_to "Visualiser", sport_path(sport) %>
      <% end %>
    </ul>
  </div>
  <div class="bouton_ajout">
    <%= link_to 'Nouvel entrainement', new_sport_path %>
  </div>
</div>

app/views/sports/new.html.erb
<div class="card">
  <div class="card-header">
    <div class="text-header">Ajouter un sport</div>
  </div>
  <div class="card-body">
    <%= simple_form_for(@sport, url: sports_path, method: :post) do |f| %>
      <%= f.input :name %>
      <%= f.input :teams %>
      <%= f.input :players %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/sports/show.html.erb
<div class="container_showsports">
  <h1>Détails du sport</h1>
  <p>Nom : <%= @sport.name %></p>
  <p>Équipes : <%= @sport.teams %></p>
  <p>Joueurs :</p>
<% @sport.players.each do |player| %>
  <div class="card">
    <p><%= player.name.strip %></p>
    <%= link_to "Joueurs", sport_player_path(@sport, player) %>
    <%= button_to "Retirer", sport_player_path(@sport, player), method: :delete, data: { turbo_confirm: "Êtes-vous sûr de vouloir retirer ce joueur ?" }, class: "btn btn-danger" %>


  </div>
<% end %>
  </div>
</div>
<br><br>
<%= link_to "Ajouter un nouveau joueur", new_sport_player_path(@sport) %>

<br><br>
<%= link_to "Supprimer", sport_path(@sport), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer ce document ?" } %>